name: Build Expo App Locally

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  build-local-android:
    name: Build Android App Locally
    runs-on: ubuntu-latest
    # Add permissions here
    permissions:
      contents: write # Required to create a GitHub Release
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo and EAS CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Configure app.json (Ensure owner is present)
        run: |
          if [ -f "app.json" ]; then
            if ! jq -e '.expo.owner' app.json > /dev/null; then
              jq '.expo.owner = "naushadraien"' app.json > app.json.tmp && mv app.json.tmp app.json
              echo "Added owner to app.json for local build"
            else
              echo "Owner field already exists in app.json."
            fi
            echo "Current app.json:"
            cat app.json
          else
            echo "ERROR: app.json not found in ./client directory!"
            exit 1
          fi

      - name: Configure eas.json for Local Build
        run: |
          cat > eas.json << EOF
          {
            "cli": {
              "version": ">= 5.9.0"
            },
            "build": {
              "local_build_profile": {
                "distribution": "internal",
                "android": {
                  "buildType": "apk",
                  "withoutCredentials": true
                },
                "env": {}
              }
            }
          }
          EOF
          echo "Created/Updated eas.json for local build profile 'local_build_profile'"

      - name: Build Android app locally
        id: local_build
        run: |
          echo "Starting local Android build..."
          bunx eas build --platform android --profile local_build_profile --local --output ./ChitChat.apk
          echo "Local build finished."
          if [ -f "./ChitChat.apk" ]; then
            echo "APK successfully created at ./ChitChat.apk"
            ls -l ./ChitChat.apk
          else
            echo "ERROR: APK file ./ChitChat.apk not found after build!"
            exit 1
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Upload APK as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ChitChat-Local-APK
          path: ./client/ChitChat.apk
          retention-days: 7

      - name: Create GitHub Release with APK
        if: success() && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        id: gh_release
        with:
          files: ./client/ChitChat.apk
          name: ChitChat Local Build v${{ github.run_number }}
          tag_name: local-v${{ github.run_number }}
          body: |
            Locally built ChitChat Mobile App (Android APK)
            Build Number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Release Download URL
        if: success() && steps.gh_release.outputs.url != '' && github.ref == 'refs/heads/main'
        run: |
          echo "---------------------------------------------------------------------"
          echo "APK available for download at the GitHub Release page:"
          echo "${{ steps.gh_release.outputs.html_url }}"
          echo "---------------------------------------------------------------------"
